common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  password:

development:
  <<: *common
  database: foursquare_mapped_development

test:
  <<: *common
  database: foursquare_mapped_test

production:
  <<: *common
  database: foursquare_mapped_production
